version: "3.7"

services:
    db:
        image: postgres:14.2-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: postgres
            POSTGRES_DB: tweeter
        ports:
            - "8080:5432"
